// Package render provides shared template rendering helpers used by all
// provider subpackages. It owns the base template FuncMap (tfid, gcpSAID) and
// the file-header comment prepended to every generated file.
package render

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// FileHeader is prepended to every generated file so the origin is always clear.
const FileHeader = "# Generated by Transcribe - SOC2 Compliant Architecture\n\n"

// RenderFile parses tmplSrc (prepending FileHeader), then writes the rendered
// result to path. extra is merged into the base FuncMap; pass nil if not needed.
func RenderFile(path, tmplSrc string, data any, extra template.FuncMap) error {
	funcs := baseFuncMap()
	for k, v := range extra {
		funcs[k] = v
	}

	t, err := template.
		New(filepath.Base(path)).
		Funcs(funcs).
		Parse(FileHeader + tmplSrc)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		// Try creating parent directories and retry once.
		if mkErr := os.MkdirAll(filepath.Dir(path), 0o755); mkErr != nil {
			return mkErr
		}
		f, err = os.Create(path)
		if err != nil {
			return err
		}
	}
	defer f.Close()

	return t.Execute(f, data)
}

// WriteFiles renders each (filename, template) pair into outputDir.
func WriteFiles(outputDir string, files []struct{ Name, Tmpl string }, data any, extra template.FuncMap) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}
	for _, f := range files {
		if err := RenderFile(filepath.Join(outputDir, f.Name), f.Tmpl, data, extra); err != nil {
			return fmt.Errorf("render %s: %w", f.Name, err)
		}
	}
	return nil
}

// baseFuncMap returns the FuncMap entries shared by all providers.
func baseFuncMap() template.FuncMap {
	return template.FuncMap{
		// tfid converts a name into a valid Terraform resource identifier by
		// replacing every hyphen with an underscore.
		"tfid": func(s string) string {
			return strings.ReplaceAll(s, "-", "_")
		},
		// gcpSAID truncates and normalises a name to fit GCP service account
		// ID constraints: lowercase letters, digits, hyphens; max 30 chars.
		"gcpSAID": func(s string) string {
			s = strings.ToLower(strings.ReplaceAll(s, "_", "-"))
			if len(s) > 30 {
				s = s[:30]
			}
			return strings.TrimRight(s, "-")
		},
	}
}
