// Package helm generates cloud-agnostic Kubernetes Helm charts from a Blueprint.
//
// Output files:
//
//	Chart.yaml                — chart metadata
//	values.yaml               — default values
//	templates/deployment.yaml — one Deployment per service
//	templates/service.yaml    — one Service per service with exposed ports
package helm

import (
	"github.com/justinclev/transcribe/internal/generator/render"
	"github.com/justinclev/transcribe/internal/models"
)

// Generate writes all Helm chart files into outputDir.
func Generate(bp *models.Blueprint, outputDir string) error {
	return render.WriteFiles(outputDir, []struct{ Name, Tmpl string }{
		{"Chart.yaml", chartTmpl},
		{"values.yaml", valuesTmpl},
		{"templates/deployment.yaml", deploymentTmpl},
		{"templates/service.yaml", serviceTmpl},
	}, bp, nil)
}

const chartTmpl = `apiVersion: v2
name: {{.Name}}
description: SOC2-compliant Kubernetes workloads for {{.Name}} — generated by Transcribe.
type: application
version: 0.1.0
appVersion: "1.0.0"
`

const valuesTmpl = `# Default values for {{.Name}}.
# Override per environment with -f values-prod.yaml or --set key=value.

replicaCount: 2

image:
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  annotations: {}

podAnnotations:
  transcribe: "true"

resources:
  requests:
    cpu:    "100m"
    memory: "128Mi"
  limits:
    cpu:    "500m"
    memory: "512Mi"

# autoscaling is disabled by default; enable per environment.
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
`

const deploymentTmpl = `{{- range .Services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ "{{" }}.Name{{ "}}" }}-{{ "{{" }} .Release.Name {{ "}}" }}
  labels:
    app.kubernetes.io/name:       {{ "{{" }} .Name {{ "}}" }}
    app.kubernetes.io/instance:   {{ "{{" }} .Release.Name {{ "}}" }}
    app.kubernetes.io/managed-by: Transcribe
spec:
  replicas: {{ "{{" }} .Values.replicaCount {{ "}}" }}
  selector:
    matchLabels:
      app.kubernetes.io/name:     {{ "{{" }} .Name {{ "}}" }}
      app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name:     {{ "{{" }} .Name {{ "}}" }}
        app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
      annotations:
        transcribe: "true"
    spec:
      serviceAccountName: {{ "{{" }} .Name {{ "}}" }}-{{ "{{" }} .Release.Name {{ "}}" }}
      containers:
        - name: {{ "{{" }} .Name {{ "}}" }}
          image: "{{ "{{" }} .Image {{ "}}" }}:{{ "{{" }} .Values.image.tag {{ "}}" }}"
          imagePullPolicy: {{ "{{" }} .Values.image.pullPolicy {{ "}}" }}
          resources: {{ "{{" }} toYaml .Values.resources | nindent 12 {{ "}}" }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem:   true
            runAsNonRoot:             true
            runAsUser:                1000
            capabilities:
              drop: ["ALL"]
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}
`

const serviceTmpl = `{{- range .Services }}
{{- if .Ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ "{{" }} .Name {{ "}}" }}-{{ "{{" }} .Release.Name {{ "}}" }}
  labels:
    app.kubernetes.io/name:     {{ "{{" }} .Name {{ "}}" }}
    app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name:     {{ "{{" }} .Name {{ "}}" }}
    app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
  ports:
    {{- range .Ports }}
    - port:       {{ . }}
      targetPort: {{ . }}
      protocol:   TCP
    {{- end }}
{{- end }}
{{- end }}
`
