package gcp

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/justinclev/transcribe/pkg/models"
)

func minimalBP() *models.Blueprint {
	return &models.Blueprint{
		Name:     "test-app",
		Provider: models.ProviderGCP,
		Region:   "us-central1",
		Network:  models.NetworkConfig{VPCCidr: "10.0.0.0/16"},
		Services: []models.Service{
			{Name: "api", CPU: 256, Memory: 512},
		},
	}
}

func TestGenerate_CreatesExpectedFiles(t *testing.T) {
	dir := t.TempDir()
	if err := Generate(minimalBP(), dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	for _, name := range []string{"main.tf", "network.tf", "iam.tf"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("missing file: %s", name)
		}
	}
}

func TestGenerate_MainTF_HasGoogleProvider(t *testing.T) {
	dir := t.TempDir()
	if err := Generate(minimalBP(), dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	b, _ := os.ReadFile(filepath.Join(dir, "main.tf"))
	if !strings.Contains(string(b), `"google"`) {
		t.Error("main.tf should declare google provider")
	}
	if !strings.Contains(string(b), "us-central1") {
		t.Error("main.tf should contain region")
	}
}

func TestGenerate_NetworkTF_HasVPC(t *testing.T) {
	dir := t.TempDir()
	if err := Generate(minimalBP(), dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	b, _ := os.ReadFile(filepath.Join(dir, "network.tf"))
	if !strings.Contains(string(b), "google_compute_network") {
		t.Error("network.tf should contain VPC network resource")
	}
}

func TestGenerate_IamTF_HasServiceAccountPerService(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Services = []models.Service{
		{Name: "api", CPU: 256, Memory: 512},
		{Name: "worker", CPU: 256, Memory: 512},
	}
	if err := Generate(bp, dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	b, _ := os.ReadFile(filepath.Join(dir, "iam.tf"))
	content := string(b)
	if !strings.Contains(content, "google_service_account") {
		t.Error("iam.tf should contain service accounts")
	}
}

func TestGenerate_AllFilesHaveFileHeader(t *testing.T) {
	dir := t.TempDir()
	if err := Generate(minimalBP(), dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	for _, name := range []string{"main.tf", "network.tf", "iam.tf"} {
		b, _ := os.ReadFile(filepath.Join(dir, name))
		if !strings.Contains(string(b), "Generated by Transcribe") {
			t.Errorf("%s missing file header", name)
		}
	}
}
