// Package pulumi generates Pulumi TypeScript programs for AWS, Azure, and GCP.
//
// Output files (same structure for all providers):
//
//	Pulumi.yaml  — project metadata
//	index.ts     — provider-specific infrastructure
//	package.json — npm dependencies
package pulumi

import (
	"fmt"

	"github.com/justinclev/transcribe/internal/generator/render"
	"github.com/justinclev/transcribe/pkg/models"
)

// Generate routes to the correct provider-specific Pulumi program.
func Generate(bp *models.Blueprint, outputDir string) error {
	switch bp.Provider {
	case models.ProviderAWS:
		return generateAWS(bp, outputDir)
	case models.ProviderAzure:
		return generateAzure(bp, outputDir)
	case models.ProviderGCP:
		return generateGCP(bp, outputDir)
	default:
		return fmt.Errorf("unsupported pulumi provider: %q", bp.Provider)
	}
}

func generateAWS(bp *models.Blueprint, outputDir string) error {
	return render.WriteFiles(outputDir, []struct{ Name, Tmpl string }{
		{"Pulumi.yaml", projectTmpl},
		{"index.ts", awsIndexTmpl},
		{"package.json", awsPackageTmpl},
	}, bp, nil)
}

func generateAzure(bp *models.Blueprint, outputDir string) error {
	return render.WriteFiles(outputDir, []struct{ Name, Tmpl string }{
		{"Pulumi.yaml", projectTmpl},
		{"index.ts", azureIndexTmpl},
		{"package.json", azurePackageTmpl},
	}, bp, nil)
}

func generateGCP(bp *models.Blueprint, outputDir string) error {
	return render.WriteFiles(outputDir, []struct{ Name, Tmpl string }{
		{"Pulumi.yaml", projectTmpl},
		{"index.ts", gcpIndexTmpl},
		{"package.json", gcpPackageTmpl},
	}, bp, nil)
}

// ---------------------------------------------------------------------------
// Shared
// ---------------------------------------------------------------------------

const projectTmpl = `name: {{.Name}}
runtime: nodejs
description: SOC2-compliant infrastructure for {{.Name}} — generated by Transcribe.
config:
  pulumi:tags:
    value:
      Transcribe: "true"
`

// ---------------------------------------------------------------------------
// AWS
// ---------------------------------------------------------------------------

const awsIndexTmpl = `import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

// ── VPC ──────────────────────────────────────────────────────────────────────

const vpc = new aws.ec2.Vpc("{{.Name}}-vpc", {
    cidrBlock:          "{{.Network.VPCCidr}}",
    enableDnsHostnames: true,
    enableDnsSupport:   true,
    tags: { Name: "{{.Name}}-vpc", Transcribe: "true" },
});

const igw = new aws.ec2.InternetGateway("{{.Name}}-igw", {
    vpcId: vpc.id,
    tags: { Name: "{{.Name}}-igw", Transcribe: "true" },
});

const azs = aws.getAvailabilityZonesOutput({ state: "available" });

const publicSubnet1 = new aws.ec2.Subnet("{{.Name}}-public-1", {
    vpcId:               vpc.id,
    cidrBlock:           pulumi.interpolate` + "`${azs.apply(a => a.names[0])}`" + `,
    availabilityZone:    azs.apply(a => a.names[0]),
    mapPublicIpOnLaunch: true,
    tags: { Name: "{{.Name}}-public-1", Transcribe: "true" },
});

const publicSubnet2 = new aws.ec2.Subnet("{{.Name}}-public-2", {
    vpcId:               vpc.id,
    cidrBlock:           pulumi.interpolate` + "`${azs.apply(a => a.names[1])}`" + `,
    availabilityZone:    azs.apply(a => a.names[1]),
    mapPublicIpOnLaunch: true,
    tags: { Name: "{{.Name}}-public-2", Transcribe: "true" },
});

const privateSubnet1 = new aws.ec2.Subnet("{{.Name}}-private-1", {
    vpcId:            vpc.id,
    cidrBlock:        pulumi.interpolate` + "`${azs.apply(a => a.names[0])}`" + `,
    availabilityZone: azs.apply(a => a.names[0]),
    tags: { Name: "{{.Name}}-private-1", Transcribe: "true" },
});

const privateSubnet2 = new aws.ec2.Subnet("{{.Name}}-private-2", {
    vpcId:            vpc.id,
    cidrBlock:        pulumi.interpolate` + "`${azs.apply(a => a.names[1])}`" + `,
    availabilityZone: azs.apply(a => a.names[1]),
    tags: { Name: "{{.Name}}-private-2", Transcribe: "true" },
});

const natEip = new aws.ec2.Eip("{{.Name}}-nat-eip", { domain: "vpc" });

const natGw = new aws.ec2.NatGateway("{{.Name}}-nat", {
    allocationId: natEip.id,
    subnetId:     publicSubnet1.id,
    tags: { Name: "{{.Name}}-nat", Transcribe: "true" },
}, { dependsOn: [igw] });

// ── IAM roles ─────────────────────────────────────────────────────────────────
{{range .Services}}
const role_{{tfid .IAMRoleName}} = new aws.iam.Role("{{.IAMRoleName}}", {
    assumeRolePolicy: JSON.stringify({
        Version: "2012-10-17",
        Statement: [{
            Effect:    "Allow",
            Principal: { Service: "ecs-tasks.amazonaws.com" },
            Action:    "sts:AssumeRole",
        }],
    }),
    tags: { Name: "{{.IAMRoleName}}", Transcribe: "true" },
});

new aws.iam.RolePolicy("{{.IAMRoleName}}-policy", {
    role: role_{{tfid .IAMRoleName}}.id,
    policy: JSON.stringify({
        Version: "2012-10-17",
        Statement: [
            {
                Sid:      "CloudWatchLogs",
                Effect:   "Allow",
                Action:   ["logs:CreateLogStream", "logs:PutLogEvents"],
                Resource: "*",
            },
            {
                Sid:      "ECRPull",
                Effect:   "Allow",
                Action:   ["ecr:GetAuthorizationToken", "ecr:BatchCheckLayerAvailability",
                           "ecr:GetDownloadUrlForLayer", "ecr:BatchGetImage"],
                Resource: "*",
            },
        ],
    }),
});
{{end}}
export const vpcId = vpc.id;
`

const awsPackageTmpl = `{
  "name": "{{.Name}}",
  "devDependencies": {
    "@types/node": "^18"
  },
  "dependencies": {
    "@pulumi/pulumi": "^3",
    "@pulumi/aws":    "^6"
  }
}
`

// ---------------------------------------------------------------------------
// Azure
// ---------------------------------------------------------------------------

const azureIndexTmpl = `import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure-native";

// ── Resource Group ────────────────────────────────────────────────────────────

const rg = new azure.resources.ResourceGroup("{{.Name}}-rg", {
    location: "{{.Region}}",
    tags: { Transcribe: "true" },
});

// ── Virtual Network ───────────────────────────────────────────────────────────

const vnet = new azure.network.VirtualNetwork("{{.Name}}-vnet", {
    resourceGroupName: rg.name,
    location:          rg.location,
    addressSpace:      { addressPrefixes: ["{{.Network.VPCCidr}}"] },
    tags: { Transcribe: "true" },
});

const publicSubnet1 = new azure.network.Subnet("{{.Name}}-public-1", {
    resourceGroupName:  rg.name,
    virtualNetworkName: vnet.name,
    addressPrefix:      "10.0.0.0/24",
});

const publicSubnet2 = new azure.network.Subnet("{{.Name}}-public-2", {
    resourceGroupName:  rg.name,
    virtualNetworkName: vnet.name,
    addressPrefix:      "10.0.1.0/24",
});

const privateSubnet1 = new azure.network.Subnet("{{.Name}}-private-1", {
    resourceGroupName:  rg.name,
    virtualNetworkName: vnet.name,
    addressPrefix:      "10.0.10.0/24",
});

const privateSubnet2 = new azure.network.Subnet("{{.Name}}-private-2", {
    resourceGroupName:  rg.name,
    virtualNetworkName: vnet.name,
    addressPrefix:      "10.0.11.0/24",
});

// ── Managed Identities ────────────────────────────────────────────────────────
{{range .Services}}
const identity_{{tfid .IAMRoleName}} = new azure.managedidentity.UserAssignedIdentity("{{.IAMRoleName}}", {
    resourceGroupName: rg.name,
    location:          rg.location,
    tags: { Name: "{{.IAMRoleName}}", Transcribe: "true" },
});
{{end}}
export const vnetId = vnet.id;
`

const azurePackageTmpl = `{
  "name": "{{.Name}}",
  "devDependencies": {
    "@types/node": "^18"
  },
  "dependencies": {
    "@pulumi/pulumi":        "^3",
    "@pulumi/azure-native":  "^2"
  }
}
`

// ---------------------------------------------------------------------------
// GCP
// ---------------------------------------------------------------------------

const gcpIndexTmpl = `import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const config = new pulumi.Config();
const projectId = config.require("projectId");

// ── VPC ──────────────────────────────────────────────────────────────────────

const network = new gcp.compute.Network("{{.Name}}-vpc", {
    autoCreateSubnetworks: false,
});

const publicSubnet1 = new gcp.compute.Subnetwork("{{.Name}}-public-1", {
    ipCidrRange: "10.0.0.0/24",
    region:      "{{.Region}}",
    network:     network.id,
});

const publicSubnet2 = new gcp.compute.Subnetwork("{{.Name}}-public-2", {
    ipCidrRange: "10.0.1.0/24",
    region:      "{{.Region}}",
    network:     network.id,
});

const privateSubnet1 = new gcp.compute.Subnetwork("{{.Name}}-private-1", {
    ipCidrRange:           "10.0.10.0/24",
    region:                "{{.Region}}",
    network:               network.id,
    privateIpGoogleAccess: true,
});

const privateSubnet2 = new gcp.compute.Subnetwork("{{.Name}}-private-2", {
    ipCidrRange:           "10.0.11.0/24",
    region:                "{{.Region}}",
    network:               network.id,
    privateIpGoogleAccess: true,
});

const router = new gcp.compute.Router("{{.Name}}-router", {
    region:  "{{.Region}}",
    network: network.id,
});

const nat = new gcp.compute.RouterNat("{{.Name}}-nat", {
    router:               router.name,
    region:               "{{.Region}}",
    natIpAllocateOption:  "AUTO_ONLY",
    sourceSubnetworkIpRangesToNat: "LIST_OF_SUBNETWORKS",
    subnetworks: [
        { name: privateSubnet1.id, sourceIpRangesToNats: ["ALL_IP_RANGES"] },
        { name: privateSubnet2.id, sourceIpRangesToNats: ["ALL_IP_RANGES"] },
    ],
});

// ── Service Accounts ──────────────────────────────────────────────────────────
{{range .Services}}
const sa_{{tfid .IAMRoleName}} = new gcp.serviceaccount.Account("{{gcpSAID .IAMRoleName}}", {
    accountId:   "{{gcpSAID .IAMRoleName}}",
    displayName: "{{.IAMRoleName}}",
    project:     projectId,
});

new gcp.projects.IAMMember("{{gcpSAID .IAMRoleName}}-logging", {
    project: projectId,
    role:    "roles/logging.logWriter",
    member:  pulumi.interpolate` + "`serviceAccount:${sa_{{tfid .IAMRoleName}}.email}`" + `,
});

new gcp.projects.IAMMember("{{gcpSAID .IAMRoleName}}-registry", {
    project: projectId,
    role:    "roles/artifactregistry.reader",
    member:  pulumi.interpolate` + "`serviceAccount:${sa_{{tfid .IAMRoleName}}.email}`" + `,
});
{{end}}
export const networkId = network.id;
`

const gcpPackageTmpl = `{
  "name": "{{.Name}}",
  "devDependencies": {
    "@types/node": "^18"
  },
  "dependencies": {
    "@pulumi/pulumi": "^3",
    "@pulumi/gcp":    "^7"
  }
}
`
