package aws

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/justinclev/transcribe/internal/models"
)

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func minimalBP() *models.Blueprint {
	return &models.Blueprint{
		Name:     "test-app",
		Provider: models.ProviderAWS,
		Region:   "us-east-1",
		Network: models.NetworkConfig{
			VPCCidr: "10.0.0.0/16",
		},
		Database: models.DatabaseConfig{Engine: models.EnginePostgres},
		Services: []models.Service{
			{Name: "api", IAMRoleName: "test-app-api-task-role", CPU: 256, Memory: 512},
		},
	}
}

func mustGenerate(t *testing.T, bp *models.Blueprint, dir string) {
	t.Helper()
	if err := Generate(bp, dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}
}

func readFile(t *testing.T, dir, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	return string(b)
}

// ---------------------------------------------------------------------------
// Generate: file creation
// ---------------------------------------------------------------------------

func TestGenerate_CreatesAllExpectedFiles(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	expected := []string{
		"main.tf", "vpc.tf", "security_groups.tf", "kms.tf", "ecr.tf",
		"logs.tf", "flow_logs.tf", "iam.tf", "ecs.tf", "alb.tf", "waf.tf",
		"rds.tf", "secrets.tf", "cloudtrail.tf", "endpoints.tf",
		"outputs.tf", "backend.tf",
	}
	for _, name := range expected {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("missing expected file: %s", name)
		}
	}
}

func TestGenerate_AllFilesHaveFileHeader(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	for _, name := range []string{"main.tf", "vpc.tf", "iam.tf", "ecs.tf"} {
		content := readFile(t, dir, name)
		if !strings.Contains(content, "Generated by Transcribe") {
			t.Errorf("%s missing file header", name)
		}
	}
}

func TestGenerate_ReturnsErrorForInvalidOutputDir(t *testing.T) {
	bp := minimalBP()
	// A file path where a directory cannot be created (parent is a file).
	tmp := t.TempDir()
	blockingFile := filepath.Join(tmp, "blocker")
	if err := os.WriteFile(blockingFile, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := Generate(bp, filepath.Join(blockingFile, "subdir"))
	if err == nil {
		t.Error("expected error for invalid output dir, got nil")
	}
}

// ---------------------------------------------------------------------------
// main.tf content
// ---------------------------------------------------------------------------

func TestGenerate_MainTF_ContainsProvider(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "main.tf")
	if !strings.Contains(content, `provider "aws"`) {
		t.Error("main.tf missing aws provider block")
	}
	if !strings.Contains(content, "us-east-1") {
		t.Error("main.tf missing region")
	}
}

func TestGenerate_MainTF_HasWorkspaceLocal(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "main.tf")
	if !strings.Contains(content, "locals {") {
		t.Error("main.tf missing locals block for workspace env")
	}
	if !strings.Contains(content, "terraform.workspace") {
		t.Error("main.tf missing terraform.workspace reference")
	}
}

func TestGenerate_MainTF_HasCallerIdentityData(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "main.tf")
	if !strings.Contains(content, `data "aws_caller_identity" "current"`) {
		t.Error("main.tf missing aws_caller_identity data source")
	}
}

func TestGenerate_MainTF_HasTranscribeDefaultTag(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "main.tf")
	if !strings.Contains(content, `Transcribe = "true"`) {
		t.Error("main.tf missing Transcribe default_tags entry")
	}
}

// ---------------------------------------------------------------------------
// vpc.tf content
// ---------------------------------------------------------------------------

func TestGenerate_VpcTF_ContainsResourceIdentifier(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Name = "my-app"
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "my_app") {
		t.Error("vpc.tf resource identifier should use underscores")
	}
}

func TestGenerate_VpcTF_UsesWorkspaceEnvPrefix(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "${local.env}-") {
		t.Error("vpc.tf Name tags should be prefixed with ${local.env}")
	}
}

// ---------------------------------------------------------------------------
// iam.tf content
// ---------------------------------------------------------------------------

func TestGenerate_IamTF_ContainsRolePerService(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Services = []models.Service{
		{Name: "api", IAMRoleName: "api-task-role", CPU: 256, Memory: 512},
		{Name: "worker", IAMRoleName: "worker-task-role", CPU: 256, Memory: 512},
	}
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "iam.tf")
	if !strings.Contains(content, "api-task-role") {
		t.Error("iam.tf missing api task role")
	}
	if !strings.Contains(content, "worker-task-role") {
		t.Error("iam.tf missing worker task role")
	}
}

func TestGenerate_IamTF_UsesWorkspaceEnvPrefix(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "iam.tf")
	if !strings.Contains(content, "${local.env}-") {
		t.Error("iam.tf role names should be prefixed with ${local.env}")
	}
}

// ---------------------------------------------------------------------------
// waf.tf — SEC-01
// ---------------------------------------------------------------------------

func TestGenerate_WafTF_OmittedWhenPrivateALB(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Network.PublicLoadBalancer = false
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "waf.tf")
	if strings.Contains(content, "aws_wafv2_web_acl") {
		t.Error("waf.tf should not define WAF when PublicLoadBalancer=false")
	}
}

func TestGenerate_WafTF_PresentWhenPublicALB(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Network.PublicLoadBalancer = true
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "waf.tf")
	if !strings.Contains(content, "aws_wafv2_web_acl") {
		t.Error("waf.tf should define WAF when PublicLoadBalancer=true")
	}
	if !strings.Contains(content, "AWSManagedRulesCommonRuleSet") {
		t.Error("waf.tf should include AWS Core Rule Set")
	}
	if !strings.Contains(content, "AWSManagedRulesSQLiRuleSet") {
		t.Error("waf.tf should include SQLi rule set")
	}
}

func TestGenerate_WafTF_LogGroupNamePrefix(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Network.PublicLoadBalancer = true
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "waf.tf")
	// AWS requires WAF log group names to start with aws-waf-logs-
	if !strings.Contains(content, "aws-waf-logs-") {
		t.Error("waf.tf WAF log group must start with aws-waf-logs-")
	}
}

// ---------------------------------------------------------------------------
// cloudtrail.tf — LOG-01
// ---------------------------------------------------------------------------

func TestGenerate_CloudtrailTF_AlwaysPresent(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "cloudtrail.tf")
	if !strings.Contains(content, "aws_cloudtrail") {
		t.Error("cloudtrail.tf should always define aws_cloudtrail resource")
	}
}

func TestGenerate_CloudtrailTF_MultiRegion(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "cloudtrail.tf")
	if !strings.Contains(content, "is_multi_region_trail") {
		t.Error("cloudtrail.tf should enable multi-region trail")
	}
}

func TestGenerate_CloudtrailTF_LogFileValidation(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "cloudtrail.tf")
	if !strings.Contains(content, "enable_log_file_validation") {
		t.Error("cloudtrail.tf should enable log file validation")
	}
}

func TestGenerate_CloudtrailTF_S3BucketUnique(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "cloudtrail.tf")
	// Bucket name should include account ID for global uniqueness
	if !strings.Contains(content, "aws_caller_identity.current.account_id") {
		t.Error("cloudtrail.tf S3 bucket name should include account_id for uniqueness")
	}
}

// ---------------------------------------------------------------------------
// endpoints.tf — NET-03
// ---------------------------------------------------------------------------

func TestGenerate_EndpointsTF_AlwaysPresent(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "endpoints.tf")
	if !strings.Contains(content, "aws_vpc_endpoint") {
		t.Error("endpoints.tf should always define VPC endpoints")
	}
}

func TestGenerate_EndpointsTF_HasECREndpoints(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "endpoints.tf")
	if !strings.Contains(content, "ecr.api") {
		t.Error("endpoints.tf missing ECR API interface endpoint")
	}
	if !strings.Contains(content, "ecr.dkr") {
		t.Error("endpoints.tf missing ECR DKR interface endpoint")
	}
}

func TestGenerate_EndpointsTF_HasSecretsManagerEndpoint(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "endpoints.tf")
	if !strings.Contains(content, "secretsmanager") {
		t.Error("endpoints.tf missing Secrets Manager interface endpoint")
	}
}

func TestGenerate_EndpointsTF_HasS3GatewayEndpoint(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "endpoints.tf")
	if !strings.Contains(content, "_s3") || !strings.Contains(content, "Gateway") {
		t.Error("endpoints.tf missing S3 gateway endpoint")
	}
}

// ---------------------------------------------------------------------------
// outputs.tf
// ---------------------------------------------------------------------------

func TestGenerate_OutputsTF_AlwaysHasVpcAndClusterOutputs(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readFile(t, dir, "outputs.tf")
	for _, want := range []string{"vpc_id", "ecs_cluster_name", "kms_key_arn", "cloudtrail_s3_bucket", "terraform_workspace"} {
		if !strings.Contains(content, want) {
			t.Errorf("outputs.tf missing output: %s", want)
		}
	}
}

func TestGenerate_OutputsTF_HasALBOutputsWhenPublic(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Network.PublicLoadBalancer = true
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "outputs.tf")
	if !strings.Contains(content, "alb_dns_name") {
		t.Error("outputs.tf should have alb_dns_name when PublicLoadBalancer=true")
	}
	if !strings.Contains(content, "waf_web_acl_arn") {
		t.Error("outputs.tf should have waf_web_acl_arn when PublicLoadBalancer=true")
	}
}

func TestGenerate_OutputsTF_HasECRUrlPerService(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Services = []models.Service{
		{Name: "api", CPU: 256, Memory: 512},
		{Name: "worker", CPU: 256, Memory: 512},
	}
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "outputs.tf")
	if !strings.Contains(content, "ecr_repo_url_api") {
		t.Error("outputs.tf missing ecr_repo_url_api")
	}
	if !strings.Contains(content, "ecr_repo_url_worker") {
		t.Error("outputs.tf missing ecr_repo_url_worker")
	}
}

func TestGenerate_OutputsTF_HasRDSEndpointForRDSEngine(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Database.Engine = models.EnginePostgres
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "outputs.tf")
	if !strings.Contains(content, "rds_endpoint") {
		t.Error("outputs.tf missing rds_endpoint for RDS engine")
	}
}

func TestGenerate_OutputsTF_HasAuroraEndpointsForAuroraEngine(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Database.Engine = models.EngineAuroraPostgres
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "outputs.tf")
	if !strings.Contains(content, "aurora_cluster_endpoint") {
		t.Error("outputs.tf missing aurora_cluster_endpoint for Aurora engine")
	}
	if !strings.Contains(content, "aurora_reader_endpoint") {
		t.Error("outputs.tf missing aurora_reader_endpoint for Aurora engine")
	}
}

// ---------------------------------------------------------------------------
// rds.tf — DATA-01 deletion protection
// ---------------------------------------------------------------------------

func TestGenerate_RdsTF_DeletionProtectionRDS(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Database.Engine = models.EnginePostgres
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "rds.tf")
	if !strings.Contains(content, "deletion_protection") || !strings.Contains(content, "true") {
		t.Error("rds.tf (RDS) must have deletion_protection = true")
	}
}

func TestGenerate_RdsTF_DeletionProtectionAurora(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Database.Engine = models.EngineAuroraPostgres
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "rds.tf")
	if !strings.Contains(content, "deletion_protection") || !strings.Contains(content, "true") {
		t.Error("rds.tf (Aurora) must have deletion_protection = true")
	}
}

func TestGenerate_RdsTF_DeletionProtectionDocDB(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Database.Engine = models.EngineDocumentDB
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "rds.tf")
	if !strings.Contains(content, "deletion_protection") || !strings.Contains(content, "true") {
		t.Error("rds.tf (DocDB) must have deletion_protection = true")
	}
}

func TestGenerate_RdsTF_DeletionProtectionNeptune(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Database.Engine = models.EngineNeptune
	mustGenerate(t, bp, dir)
	content := readFile(t, dir, "rds.tf")
	if !strings.Contains(content, "deletion_protection") || !strings.Contains(content, "true") {
		t.Error("rds.tf (Neptune) must have deletion_protection = true")
	}
}

// ---------------------------------------------------------------------------
// dbPort helper
// ---------------------------------------------------------------------------

func TestDbPort(t *testing.T) {
	cases := []struct {
		engine models.DatabaseEngine
		want   string
	}{
		{models.EnginePostgres, "5432"},
		{models.EngineAuroraPostgres, "5432"},
		{models.EngineMySQL, "3306"},
		{models.EngineAuroraMySQL, "3306"},
		{models.EngineMariaDB, "3306"},
		{models.EngineSQLServer, "1433"},
		{models.EngineOracle, "1521"},
		{models.EngineDocumentDB, "27017"},
		{models.EngineRedis, "6379"},
		{models.EngineMemcached, "11211"},
		{models.EngineNeptune, "8182"},
		{models.EngineDynamoDB, "5432"}, // unknown → default postgres port
	}
	for _, tc := range cases {
		t.Run(string(tc.engine), func(t *testing.T) {
			if got := dbPort(tc.engine); got != tc.want {
				t.Errorf("dbPort(%s) = %s, want %s", tc.engine, got, tc.want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// engine classifier helpers
// ---------------------------------------------------------------------------

func TestIsRDS(t *testing.T) {
	rdsCases := []models.DatabaseEngine{
		models.EnginePostgres, models.EngineMySQL, models.EngineMariaDB,
		models.EngineOracle, models.EngineSQLServer,
	}
	for _, e := range rdsCases {
		if !isRDS(e) {
			t.Errorf("isRDS(%s) should be true", e)
		}
	}
	nonRDS := []models.DatabaseEngine{
		models.EngineAuroraPostgres, models.EngineAuroraMySQL,
		models.EngineDocumentDB, models.EngineRedis, models.EngineDynamoDB,
	}
	for _, e := range nonRDS {
		if isRDS(e) {
			t.Errorf("isRDS(%s) should be false", e)
		}
	}
}

func TestIsAurora(t *testing.T) {
	if !isAurora(models.EngineAuroraPostgres) {
		t.Error("isAurora(aurora-postgres) should be true")
	}
	if !isAurora(models.EngineAuroraMySQL) {
		t.Error("isAurora(aurora-mysql) should be true")
	}
	if isAurora(models.EnginePostgres) {
		t.Error("isAurora(postgres) should be false")
	}
}

func TestEngineClassifiers(t *testing.T) {
	if !isDocDB(models.EngineDocumentDB) {
		t.Error("isDocDB")
	}
	if !isRedis(models.EngineRedis) {
		t.Error("isRedis")
	}
	if !isMemcached(models.EngineMemcached) {
		t.Error("isMemcached")
	}
	if !isDynamoDB(models.EngineDynamoDB) {
		t.Error("isDynamoDB")
	}
	if !isNeptune(models.EngineNeptune) {
		t.Error("isNeptune")
	}
	if !isCassandra(models.EngineCassandra) {
		t.Error("isCassandra")
	}
	if !isTimestream(models.EngineTimestream) {
		t.Error("isTimestream")
	}
}

// ---------------------------------------------------------------------------
// rdsEngine / rdsEngineVersion / rdsLogExport
// ---------------------------------------------------------------------------

func TestRdsEngine(t *testing.T) {
	cases := []struct {
		engine models.DatabaseEngine
		want   string
	}{
		{models.EnginePostgres, "postgres"},
		{models.EngineMySQL, "mysql"},
		{models.EngineMariaDB, "mariadb"},
		{models.EngineOracle, "oracle-se2"},
		{models.EngineSQLServer, "sqlserver-ex"},
	}
	for _, tc := range cases {
		if got := rdsEngine(tc.engine); got != tc.want {
			t.Errorf("rdsEngine(%s) = %s, want %s", tc.engine, got, tc.want)
		}
	}
}

func TestRdsEngineVersion(t *testing.T) {
	cases := []struct {
		engine models.DatabaseEngine
		want   string
	}{
		{models.EnginePostgres, "16.1"},
		{models.EngineMySQL, "8.0"},
		{models.EngineMariaDB, "10.11"},
		{models.EngineOracle, "19"},
		{models.EngineSQLServer, "15.00"},
	}
	for _, tc := range cases {
		if got := rdsEngineVersion(tc.engine); got != tc.want {
			t.Errorf("rdsEngineVersion(%s) = %s, want %s", tc.engine, got, tc.want)
		}
	}
}

func TestRdsLogExport(t *testing.T) {
	if got := rdsLogExport(models.EngineMySQL); got != "error" {
		t.Errorf("rdsLogExport(mysql) = %s, want error", got)
	}
	if got := rdsLogExport(models.EnginePostgres); got != "postgresql" {
		t.Errorf("rdsLogExport(postgres) = %s, want postgresql", got)
	}
	if got := rdsLogExport(models.EngineSQLServer); got != "error" {
		t.Errorf("rdsLogExport(sqlserver) = %s, want error", got)
	}
}

// ---------------------------------------------------------------------------
// auroraEngine / auroraEngineVersion
// ---------------------------------------------------------------------------

func TestAuroraEngine(t *testing.T) {
	if got := auroraEngine(models.EngineAuroraMySQL); got != "aurora-mysql" {
		t.Errorf("auroraEngine(aurora-mysql) = %s, want aurora-mysql", got)
	}
	if got := auroraEngine(models.EngineAuroraPostgres); got != "aurora-postgresql" {
		t.Errorf("auroraEngine(aurora-postgres) = %s, want aurora-postgresql", got)
	}
}

func TestAuroraEngineVersion(t *testing.T) {
	if got := auroraEngineVersion(models.EngineAuroraMySQL); got != "8.0.mysql_aurora.3.05.0" {
		t.Errorf("auroraEngineVersion(aurora-mysql) = %s", got)
	}
	if got := auroraEngineVersion(models.EngineAuroraPostgres); got != "16.1" {
		t.Errorf("auroraEngineVersion(aurora-postgres) = %s", got)
	}
}

// ---------------------------------------------------------------------------
// firstPort helper
// ---------------------------------------------------------------------------

func TestFirstPort(t *testing.T) {
	cases := []struct {
		ports []string
		want  string
	}{
		{nil, "80"},
		{[]string{}, "80"},
		{[]string{"8080"}, "8080"},
		{[]string{"80:8080"}, "8080"},
		{[]string{"443:8443", "80:8080"}, "8443"}, // only first entry
	}
	for _, tc := range cases {
		if got := firstPort(tc.ports); got != tc.want {
			t.Errorf("firstPort(%v) = %s, want %s", tc.ports, got, tc.want)
		}
	}
}

// ---------------------------------------------------------------------------
// add100 helper
// ---------------------------------------------------------------------------

func TestAdd100(t *testing.T) {
	cases := []struct {
		in   int
		want string
	}{{0, "100"}, {5, "105"}, {99, "199"}}
	for _, tc := range cases {
		if got := add100(tc.in); got != tc.want {
			t.Errorf("add100(%d) = %s, want %s", tc.in, got, tc.want)
		}
	}
}

// ---------------------------------------------------------------------------
// isSensitiveVar helper
// ---------------------------------------------------------------------------

func TestIsSensitiveVar(t *testing.T) {
	sensitive := []string{
		"DB_PASSWORD", "API_KEY", "SECRET_TOKEN", "aws_secret_access_key",
		"PRIVATE_KEY", "DB_PASSWD", "CREDENTIALS", "CERT_FILE",
	}
	for _, name := range sensitive {
		if !isSensitiveVar(name) {
			t.Errorf("isSensitiveVar(%q) should be true", name)
		}
	}
	nonSensitive := []string{"DATABASE_URL", "PORT", "LOG_LEVEL", "APP_NAME"}
	for _, name := range nonSensitive {
		if isSensitiveVar(name) {
			t.Errorf("isSensitiveVar(%q) should be false", name)
		}
	}
}

// ---------------------------------------------------------------------------
// list helper
// ---------------------------------------------------------------------------

func TestList(t *testing.T) {
	result := list("hello")
	if len(result) != 1 || result[0] != "hello" {
		t.Errorf("list(\"hello\") = %v, want [\"hello\"]", result)
	}
}
