package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/justinclev/transcribe/pkg/models"
)

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func minimalBP() *models.Blueprint {
	return &models.Blueprint{
		Name:   "test-app",
		Region: "eu-west-1",
		Network: models.NetworkConfig{
			VPCCidr: "10.1.0.0/16",
		},
		Database: models.DatabaseConfig{Engine: models.EnginePostgres},
		Services: []models.Service{
			{Name: "api", IAMRoleName: "test-app-api-task-role"},
			{Name: "worker", IAMRoleName: "test-app-worker-task-role"},
		},
	}
}

func readTestFile(t *testing.T, dir, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	return string(b)
}

func mustGenerate(t *testing.T, bp *models.Blueprint, dir string) {
	t.Helper()
	if err := Generate(bp, dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}
}

// ---------------------------------------------------------------------------
// File creation
// ---------------------------------------------------------------------------

func TestGenerate_CreatesAllThreeFiles(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	for _, name := range []string{"main.tf", "vpc.tf", "iam.tf"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("missing file %s: %v", name, err)
		}
	}
}

func TestGenerate_CreatesNestedOutputDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "deep", "out")
	mustGenerate(t, minimalBP(), dir)
	if _, err := os.Stat(dir); err != nil {
		t.Errorf("output dir not created: %v", err)
	}
}

func TestGenerate_OverwritesExistingFiles(t *testing.T) {
	dir := t.TempDir()
	bp1 := minimalBP()
	bp1.Region = "eu-west-1"
	mustGenerate(t, bp1, dir)

	bp2 := minimalBP()
	bp2.Region = "ap-northeast-1"
	mustGenerate(t, bp2, dir)

	content := readTestFile(t, dir, "main.tf")
	if !strings.Contains(content, `"ap-northeast-1"`) {
		t.Error("main.tf not overwritten with new region")
	}
	if strings.Contains(content, `"eu-west-1"`) {
		t.Error("main.tf still contains stale region after overwrite")
	}
}

// ---------------------------------------------------------------------------
// File header
// ---------------------------------------------------------------------------

func TestGenerate_FileHeader_PresentInAllFiles(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	for _, name := range []string{"main.tf", "vpc.tf", "iam.tf"} {
		content := readTestFile(t, dir, name)
		if !strings.Contains(content, "Generated by Transcribe - SOC2 Compliant Architecture") {
			t.Errorf("%s: file header missing", name)
		}
	}
}

// ---------------------------------------------------------------------------
// main.tf
// ---------------------------------------------------------------------------

func TestGenerate_MainTF_ContainsProviderBlock(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "main.tf")
	for _, want := range []string{
		`provider "aws"`,
		`source  = "hashicorp/aws"`,
		`required_providers`,
	} {
		if !strings.Contains(content, want) {
			t.Errorf("main.tf missing %q", want)
		}
	}
}

func TestGenerate_MainTF_CorrectRegion(t *testing.T) {
	for _, region := range []string{"us-east-1", "us-west-2", "eu-central-1", "ap-southeast-2"} {
		region := region
		t.Run(region, func(t *testing.T) {
			dir := t.TempDir()
			bp := minimalBP()
			bp.Region = region
			mustGenerate(t, bp, dir)
			content := readTestFile(t, dir, "main.tf")
			if !strings.Contains(content, region) {
				t.Errorf("main.tf missing region %q", region)
			}
		})
	}
}

func TestGenerate_MainTF_TranscribeDefaultTag(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "main.tf")
	if !strings.Contains(content, `Transcribe = "true"`) {
		t.Errorf("main.tf missing Transcribe default tag:\n%s", content)
	}
}

func TestGenerate_MainTF_DefaultTagsBlock(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "main.tf")
	if !strings.Contains(content, "default_tags") {
		t.Errorf("main.tf missing default_tags block:\n%s", content)
	}
}

func TestGenerate_MainTF_ProviderVersionConstraint(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "main.tf")
	// Version constraint should pin to major 5
	if !strings.Contains(content, "~> 5.0") {
		t.Errorf("main.tf missing AWS provider version constraint:\n%s", content)
	}
}

// ---------------------------------------------------------------------------
// vpc.tf
// ---------------------------------------------------------------------------

func TestGenerate_VPCTF_ContainsVPCCidr(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Network.VPCCidr = "192.168.0.0/16"
	mustGenerate(t, bp, dir)
	content := readTestFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "192.168.0.0/16") {
		t.Errorf("vpc.tf missing CIDR block:\n%s", content)
	}
}

func TestGenerate_VPCTF_HasTwoPublicSubnets(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	for _, want := range []string{"public_1", "public_2"} {
		if !strings.Contains(content, want) {
			t.Errorf("vpc.tf missing %q", want)
		}
	}
}

func TestGenerate_VPCTF_HasTwoPrivateSubnets(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	for _, want := range []string{"private_1", "private_2"} {
		if !strings.Contains(content, want) {
			t.Errorf("vpc.tf missing %q", want)
		}
	}
}

func TestGenerate_VPCTF_PublicSubnetsHavePublicIP(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "map_public_ip_on_launch = true") {
		t.Errorf("vpc.tf public subnets missing map_public_ip_on_launch:\n%s", content)
	}
}

func TestGenerate_VPCTF_HasInternetGateway(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "aws_internet_gateway") {
		t.Errorf("vpc.tf missing aws_internet_gateway")
	}
}

func TestGenerate_VPCTF_HasNATGateway(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "aws_nat_gateway") {
		t.Errorf("vpc.tf missing aws_nat_gateway")
	}
}

func TestGenerate_VPCTF_HasEIP(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "aws_eip") {
		t.Errorf("vpc.tf missing aws_eip for NAT gateway")
	}
}

func TestGenerate_VPCTF_HasRouteTables(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	for _, want := range []string{"aws_route_table", "aws_route_table_association"} {
		if !strings.Contains(content, want) {
			t.Errorf("vpc.tf missing %q", want)
		}
	}
}

func TestGenerate_VPCTF_HasAZDataSource(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "aws_availability_zones") {
		t.Errorf("vpc.tf missing availability zones data source")
	}
}

func TestGenerate_VPCTF_HyphenNameSanitized(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Name = "my-app-prod"
	mustGenerate(t, bp, dir)
	content := readTestFile(t, dir, "vpc.tf")
	// Resource identifiers must use underscores not hyphens
	if !strings.Contains(content, "my_app_prod") {
		t.Errorf("vpc.tf missing sanitized identifier my_app_prod")
	}
	// The Name tag value still uses hyphens (human-readable)
	if !strings.Contains(content, `"my-app-prod-vpc"`) {
		t.Errorf("vpc.tf Name tag should retain hyphens for readability")
	}
}

func TestGenerate_VPCTF_DNSEnabled(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "vpc.tf")
	for _, want := range []string{"enable_dns_hostnames = true", "enable_dns_support   = true"} {
		if !strings.Contains(content, want) {
			t.Errorf("vpc.tf missing %q", want)
		}
	}
}

// ---------------------------------------------------------------------------
// iam.tf
// ---------------------------------------------------------------------------

func TestGenerate_IAMTF_HasRolePerService(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "iam.tf")
	// IAM role resource identifiers use underscores (via tfid)
	for _, roleName := range []string{"test_app_api_task_role", "test_app_worker_task_role"} {
		if !strings.Contains(content, roleName) {
			t.Errorf("iam.tf missing role resource %q:\n%s", roleName, content)
		}
	}
}

func TestGenerate_IAMTF_HasPolicyPerService(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "iam.tf")
	if strings.Count(content, "aws_iam_role_policy") < 2 {
		t.Errorf("iam.tf should have at least 2 aws_iam_role_policy blocks:\n%s", content)
	}
}

func TestGenerate_IAMTF_ECSTrustPolicy(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "iam.tf")
	if !strings.Contains(content, "ecs-tasks.amazonaws.com") {
		t.Errorf("iam.tf missing ECS task trust relationship")
	}
	if !strings.Contains(content, "sts:AssumeRole") {
		t.Errorf("iam.tf missing sts:AssumeRole action")
	}
}

func TestGenerate_IAMTF_LeastPrivilegePermissions(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "iam.tf")
	for _, perm := range []string{
		"logs:CreateLogStream",
		"logs:PutLogEvents",
		"ecr:GetAuthorizationToken",
		"ecr:BatchCheckLayerAvailability",
		"ecr:GetDownloadUrlForLayer",
		"ecr:BatchGetImage",
	} {
		if !strings.Contains(content, perm) {
			t.Errorf("iam.tf missing permission %q", perm)
		}
	}
}

func TestGenerate_IAMTF_NoServices_ValidEmptyFile(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Services = nil
	if err := Generate(bp, dir); err != nil {
		t.Fatalf("Generate with no services: %v", err)
	}
	content := readTestFile(t, dir, "iam.tf")
	if !strings.Contains(content, "Generated by Transcribe") {
		t.Error("iam.tf file header missing even with no services")
	}
	if strings.Contains(content, "aws_iam_role") {
		t.Error("iam.tf should contain no role resources when services is empty")
	}
}

func TestGenerate_IAMTF_SingleService(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Services = []models.Service{
		{Name: "only-svc", IAMRoleName: "myapp-only-svc-task-role"},
	}
	mustGenerate(t, bp, dir)
	content := readTestFile(t, dir, "iam.tf")
	if !strings.Contains(content, "myapp_only_svc_task_role") {
		t.Errorf("iam.tf missing sanitized role identifier:\n%s", content)
	}
}

func TestGenerate_IAMTF_RoleNameTag(t *testing.T) {
	dir := t.TempDir()
	mustGenerate(t, minimalBP(), dir)
	content := readTestFile(t, dir, "iam.tf")
	// The human-readable Name tag retains hyphens
	if !strings.Contains(content, `"test-app-api-task-role"`) {
		t.Errorf("iam.tf role Name tag should retain hyphens:\n%s", content)
	}
}

// ---------------------------------------------------------------------------
// tfid helper (tested indirectly via output)
// ---------------------------------------------------------------------------

func TestGenerate_TfidConversion_InVPC(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Name = "complex-app-name-v2"
	mustGenerate(t, bp, dir)
	content := readTestFile(t, dir, "vpc.tf")
	if !strings.Contains(content, "complex_app_name_v2") {
		t.Errorf("vpc.tf resource identifiers not correctly sanitized:\n%s", content)
	}
}

func TestGenerate_TfidConversion_InIAM(t *testing.T) {
	dir := t.TempDir()
	bp := minimalBP()
	bp.Services = []models.Service{
		{Name: "my-service", IAMRoleName: "my-app-my-service-task-role"},
	}
	mustGenerate(t, bp, dir)
	content := readTestFile(t, dir, "iam.tf")
	if !strings.Contains(content, "my_app_my_service_task_role") {
		t.Errorf("iam.tf resource identifiers not correctly sanitized:\n%s", content)
	}
}

// Passing a regular file path as outputDir causes MkdirAll to fail because
// it cannot convert an existing file into a directory.
func TestGenerate_OutputDirIsFile_ReturnsError(t *testing.T) {
	blocked := filepath.Join(t.TempDir(), "not-a-dir")
	if err := os.WriteFile(blocked, []byte("i am a file"), 0o644); err != nil {
		t.Fatalf("setup: %v", err)
	}
	if err := Generate(minimalBP(), blocked); err == nil {
		t.Fatal("expected error when output path is an existing file, got nil")
	}
}

// Making the output dir read-only causes os.Create to fail inside renderFile,
// covering the error-return path of both renderFile and Generate.
// Skipped when running as root (e.g. inside Docker) because root ignores
// file-mode permission bits.
func TestGenerate_ReadOnlyOutputDir_ReturnsError(t *testing.T) {
	if os.Getuid() == 0 {
		t.Skip("skipping read-only dir test: running as root")
	}
	dir := t.TempDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("setup mkdir: %v", err)
	}
	// Remove write permission so os.Create fails for the .tf files.
	if err := os.Chmod(dir, 0o555); err != nil {
		t.Fatalf("setup chmod: %v", err)
	}
	defer os.Chmod(dir, 0o755) // restore so t.TempDir cleanup works
	if err := Generate(minimalBP(), dir); err == nil {
		t.Fatal("expected error writing to read-only dir, got nil")
	}
}
