// Package generator renders a hardened Blueprint into SOC2-compliant Terraform
// HCL files.  Call Generate after running the hardener; the output directory is
// created automatically.
//
// Output files:
//
//	main.tf  — AWS provider + Terraform block
//	vpc.tf   — VPC, subnets (2 public + 2 private), IGW, NAT GW, route tables
//	iam.tf   — ECS task IAM role + inline policy for every service
package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/justinclev/transcribe/pkg/models"
)

// fileHeader is prepended to every generated file so the origin is always clear.
const fileHeader = "# Generated by Transcribe - SOC2 Compliant Architecture\n\n"

// Generate writes main.tf, vpc.tf, and iam.tf into outputDir for bp.
// The directory is created with mode 0755 if it does not already exist.
func Generate(bp *models.Blueprint, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	files := []struct {
		name string
		tmpl string
	}{
		{"main.tf", mainTmpl},
		{"vpc.tf", vpcTmpl},
		{"iam.tf", iamTmpl},
	}

	for _, f := range files {
		if err := renderFile(filepath.Join(outputDir, f.name), f.tmpl, bp); err != nil {
			return fmt.Errorf("render %s: %w", f.name, err)
		}
	}
	return nil
}

// renderFile parses tmplSrc (prepending the standard file header), then writes
// the rendered result to path, overwriting any existing content.
func renderFile(path, tmplSrc string, data any) error {
	t, err := template.
		New(filepath.Base(path)).
		Funcs(template.FuncMap{
			// tfid converts a name into a valid Terraform resource identifier by
			// replacing every hyphen with an underscore.
			"tfid": func(s string) string {
				return strings.ReplaceAll(s, "-", "_")
			},
		}).
		Parse(fileHeader + tmplSrc)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	return t.Execute(f, data)
}

// ---------------------------------------------------------------------------
// Terraform templates
// ---------------------------------------------------------------------------

// mainTmpl renders main.tf: the AWS provider pinned to bp.Region.
// default_tags ensures every resource inherits Transcribe = "true" without
// repetition, satisfying the tagging requirement across all resource types.
const mainTmpl = `terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "{{.Region}}"

  default_tags {
    tags = {
      Transcribe = "true"
    }
  }
}
`

// vpcTmpl renders vpc.tf: VPC, 2 public subnets, 2 private subnets, an
// Internet Gateway, a NAT Gateway (in public subnet 1), and the associated
// route tables — all derived from bp.Network.VPCCidr.
//
// cidrsubnet newbits=8 yields /24 subnets from a typical /16 VPC CIDR.
// Indices 0-1 → public; 10-11 → private (avoids overlap if the VPC is later
// expanded into the 2-9 range).
const vpcTmpl = `locals {
  vpc_cidr = "{{.Network.VPCCidr}}"
}

data "aws_availability_zones" "available" {
  state = "available"
}

# ── VPC ──────────────────────────────────────────────────────────────────────

resource "aws_vpc" "{{tfid .Name}}" {
  cidr_block           = local.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name = "{{.Name}}-vpc"
  }
}

# ── Internet Gateway ──────────────────────────────────────────────────────────

resource "aws_internet_gateway" "{{tfid .Name}}" {
  vpc_id = aws_vpc.{{tfid .Name}}.id

  tags = {
    Name = "{{.Name}}-igw"
  }
}

# ── Public Subnets ────────────────────────────────────────────────────────────

resource "aws_subnet" "{{tfid .Name}}_public_1" {
  vpc_id                  = aws_vpc.{{tfid .Name}}.id
  cidr_block              = cidrsubnet(local.vpc_cidr, 8, 0)
  availability_zone       = data.aws_availability_zones.available.names[0]
  map_public_ip_on_launch = true

  tags = {
    Name = "{{.Name}}-public-1"
  }
}

resource "aws_subnet" "{{tfid .Name}}_public_2" {
  vpc_id                  = aws_vpc.{{tfid .Name}}.id
  cidr_block              = cidrsubnet(local.vpc_cidr, 8, 1)
  availability_zone       = data.aws_availability_zones.available.names[1]
  map_public_ip_on_launch = true

  tags = {
    Name = "{{.Name}}-public-2"
  }
}

# ── Private Subnets ───────────────────────────────────────────────────────────

resource "aws_subnet" "{{tfid .Name}}_private_1" {
  vpc_id            = aws_vpc.{{tfid .Name}}.id
  cidr_block        = cidrsubnet(local.vpc_cidr, 8, 10)
  availability_zone = data.aws_availability_zones.available.names[0]

  tags = {
    Name = "{{.Name}}-private-1"
  }
}

resource "aws_subnet" "{{tfid .Name}}_private_2" {
  vpc_id            = aws_vpc.{{tfid .Name}}.id
  cidr_block        = cidrsubnet(local.vpc_cidr, 8, 11)
  availability_zone = data.aws_availability_zones.available.names[1]

  tags = {
    Name = "{{.Name}}-private-2"
  }
}

# ── NAT Gateway (private-subnet egress) ──────────────────────────────────────

resource "aws_eip" "{{tfid .Name}}_nat" {
  domain = "vpc"

  tags = {
    Name = "{{.Name}}-nat-eip"
  }
}

resource "aws_nat_gateway" "{{tfid .Name}}" {
  allocation_id = aws_eip.{{tfid .Name}}_nat.id
  subnet_id     = aws_subnet.{{tfid .Name}}_public_1.id
  depends_on    = [aws_internet_gateway.{{tfid .Name}}]

  tags = {
    Name = "{{.Name}}-nat"
  }
}

# ── Route Tables ──────────────────────────────────────────────────────────────

resource "aws_route_table" "{{tfid .Name}}_public" {
  vpc_id = aws_vpc.{{tfid .Name}}.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.{{tfid .Name}}.id
  }

  tags = {
    Name = "{{.Name}}-public-rt"
  }
}

resource "aws_route_table_association" "{{tfid .Name}}_public_1" {
  subnet_id      = aws_subnet.{{tfid .Name}}_public_1.id
  route_table_id = aws_route_table.{{tfid .Name}}_public.id
}

resource "aws_route_table_association" "{{tfid .Name}}_public_2" {
  subnet_id      = aws_subnet.{{tfid .Name}}_public_2.id
  route_table_id = aws_route_table.{{tfid .Name}}_public.id
}

resource "aws_route_table" "{{tfid .Name}}_private" {
  vpc_id = aws_vpc.{{tfid .Name}}.id

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.{{tfid .Name}}.id
  }

  tags = {
    Name = "{{.Name}}-private-rt"
  }
}

resource "aws_route_table_association" "{{tfid .Name}}_private_1" {
  subnet_id      = aws_subnet.{{tfid .Name}}_private_1.id
  route_table_id = aws_route_table.{{tfid .Name}}_private.id
}

resource "aws_route_table_association" "{{tfid .Name}}_private_2" {
  subnet_id      = aws_subnet.{{tfid .Name}}_private_2.id
  route_table_id = aws_route_table.{{tfid .Name}}_private.id
}
`

// iamTmpl renders iam.tf: one aws_iam_role + aws_iam_role_policy per service.
// The trust policy allows ecs-tasks.amazonaws.com to assume the role.
// The inline policy grants the minimum permissions for ECS task execution:
// CloudWatch log emission and ECR image pull.
const iamTmpl = `{{- range .Services}}
# ── {{.Name}} ─────────────────────────────────────────────────────────────────

resource "aws_iam_role" "{{tfid .IAMRoleName}}" {
  name = "{{.IAMRoleName}}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Principal = { Service = "ecs-tasks.amazonaws.com" }
        Action    = "sts:AssumeRole"
      },
    ]
  })

  tags = {
    Name = "{{.IAMRoleName}}"
  }
}

resource "aws_iam_role_policy" "{{tfid .IAMRoleName}}" {
  name = "{{.IAMRoleName}}-policy"
  role = aws_iam_role.{{tfid .IAMRoleName}}.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "CloudWatchLogs"
        Effect = "Allow"
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ]
        Resource = "*"
      },
      {
        Sid    = "ECRPull"
        Effect = "Allow"
        Action = [
          "ecr:GetAuthorizationToken",
          "ecr:BatchCheckLayerAvailability",
          "ecr:GetDownloadUrlForLayer",
          "ecr:BatchGetImage",
        ]
        Resource = "*"
      },
    ]
  })
}
{{end}}`
